In [ ]:
!pip install praw

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting praw
  Downloading praw-7.7.0-py3-none-any.whl (189 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.4/189.4 kB 8.2 MB/s eta 0:00:00
Collecting prawcore<3,>=2.1 (from praw)
  Downloading prawcore-2.3.0-py3-none-any.whl (16 kB)
Collecting update-checker>=0.18 (from praw)
  Downloading update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Requirement already satisfied: websocket-client>=0.54.0 in /usr/local/lib/python3.10/dist-packages (from praw) (1.5.1)
Requirement already satisfied: requests<3.0,>=2.6.0 in /usr/local/lib/python3.10/dist-packages (from prawcore<3,>=2.1->praw) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (3.4)
Installing collected packages: update-checker, prawcore, praw
Successfully installed praw-7.7.0 prawcore-2.3.0 update-checker-0.18.0

In [ ]:
import praw
import pandas as pd

In [ ]:
reddit = praw.Reddit(client_id='MKRCcy5jZZAQpz29sXq0bw', client_secret='dLN5PNDUs_hx5v-auIz0FdOBWzNDnw', user_agent='WebScraping')

In [ ]:
hot_posts = reddit.subreddit('stocks').top('week', limit=10)
for post in hot_posts:
    print(post.title)

<ipython-input-32-3df08327af56>:1: DeprecationWarning: Positional arguments for 'BaseListingMixin.top' will no longer be supported in PRAW 8.
Call this function with 'time_filter' as a keyword argument.
  hot_posts = reddit.subreddit('stocks').top('week', limit=10)
WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Cathie Wood's ARK Invest sold most of its Nvidia stake just before the chipmaker kicked off a rally that added $585 billion in market value
What would you do? Currently holding 1.1 million in Google stock which husband accumulated over the past 12 years of working there.
Nvidia hits $1 trillion market cap
White House and Republicans reach a tentative deal to avoid U.S. default
Tesla plummets 50 spots in a survey of the US's most reputable brands. It's now No. 62 — 30 places below Ford.
NVIDIA beat earnings, top expectations.
thank god earnings season is over so we don't have to hear about AI anymore. Every company made a token AI statement to cushion blow
I introduced my mother to stocks recently, she then proceeds to hold SQQQ for the past four months, losing $500k and counting
Inflation rose 0.4% in April and 4.7% from a year ago, according to key gauge for the Fed
Ford EVs will use Tesla charging tech in surprise partnership between rivals

In [ ]:
df = []
stock_subreddit = reddit.subreddit('stocks')
for post in stock_subreddit.top('week', limit=10):
    df.append([post.title, post.score, post.id, post.subreddit, post.url, post.num_comments, post.selftext, post.created])
df = pd.DataFrame(df,columns=['title', 'score', 'id', 'subreddit', 'url', 'num_comments', 'body', 'created'])

<ipython-input-33-b6566e014041>:3: DeprecationWarning: Positional arguments for 'BaseListingMixin.top' will no longer be supported in PRAW 8.
Call this function with 'time_filter' as a keyword argument.
  for post in stock_subreddit.top('week', limit=10):
WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

In [ ]:
df

,title,score,id,subreddit,url,num_comments,body,created
0,Cathie Wood's ARK Invest sold most of its Nvid...,2336,13rxgz6,stocks,https://www.reddit.com/r/stocks/comments/13rxg...,398,Cathie Wood's Ark Invest is probably wishing i...,1.685059e+09
1,What would you do? Currently holding 1.1 milli...,1505,13v7ipk,stocks,https://www.reddit.com/r/stocks/comments/13v7i...,1402,"He doesn't work at Google anymore, so no more ...",1.685397e+09
2,Nvidia hits $1 trillion market cap,1379,13vr1zd,stocks,https://www.reddit.com/r/stocks/comments/13vr1...,475,https://www.cnbc.com/2023/05/30/nvidia-on-trac...,1.685455e+09
3,White House and Republicans reach a tentative ...,1213,13tnphs,stocks,https://www.reddit.com/r/stocks/comments/13tnp...,488,https://www.cnbc.com/2023/05/27/white-house-an...,1.685236e+09
4,Tesla plummets 50 spots in a survey of the US'...,1206,13rgzj5,stocks,https://www.reddit.com/r/stocks/comments/13rgz...,688,The automaker's dip comes as competitor Ford M...,1.685019e+09
5,"NVIDIA beat earnings, top expectations.",1171,13qwxsw,stocks,https://www.reddit.com/r/stocks/comments/13qwx...,859,Nvidia reported its fiscal first quarter earni...,1.684961e+09
6,thank god earnings season is over so we don't ...,897,13sz4l3,stocks,https://www.reddit.com/r/stocks/comments/13sz4...,217,example: Best Buy\n\nBest Buy somehow can see ...,1.685166e+09
7,"I introduced my mother to stocks recently, she...",888,13vjf02,stocks,https://www.reddit.com/r/stocks/comments/13vjf...,344,"It started off nice and good with some google,...",1.685431e+09
8,Inflation rose 0.4% in April and 4.7% from a y...,778,13sccpe,stocks,https://www.reddit.com/r/stocks/comments/13scc...,267,https://www.cnbc.com/2023/05/26/inflation-rose...,1.685105e+09
9,Ford EVs will use Tesla charging tech in surpr...,530,13ruc5g,stocks,https://www.reddit.com/r/stocks/comments/13ruc...,163,https://www.cnbc.com/2023/05/25/tesla-elon-mus...,1.685051e+09

In [ ]:
df.dtypes

title            object
score             int64
id               object
subreddit        object
url              object
num_comments      int64
body             object
created         float64
dtype: object

In [ ]:
df['body'][0]

'Cathie Wood\'s Ark Invest is probably wishing it didn\'t sell nearly 1 million shares of Nvidia between early October and today following the chipmaker\'s massive year-to-date surge of more than 160%.\n\nNvidia stock soared as much as 30% on Thursday after the company announced jaw-dropping guidance as it benefits from a wave of demand for its chipsets that support generative AI technology platforms like OpenAI\'s ChatGPT and Alphabet\'s Bard.\n\nBut the active investment manager, who has owned Nvidia on and off since the flagship fund\'s inception in 2014, missed out on massive gains as it started to pare down its position in Nvidia heading into a 52-week low in mid-October.\n\nSince Ark Invest\'s first sale on October 5, when it held 1.3 million shares of Nvidia across all of its ETFs, the stock has soared 190% and added $620 billion to its market value. By late November, Nvidia owned just over 500,000 shares of the company.\n\nToday, Ark Invest holds just 390,000 shares across its suite of next-generation technology ETFs. The stock is not in its flagship Disruptive Innovation fund.\n\nRough calculations by Insider suggest Ark Invest left more than $200 million in potential profits on the table when it sold down its Nvidia stake throughout the end of last year. \n\nArk\'s ill-timed share sale of Nvidia highlights the difficulties of actively managing a portfolio of disruption-focused investments, because even if you pick the right theme to invest in, there\'s no guarantee you\'ll pick the right companies to bet on.\n\n**In February, Wood said Ark\'s wave of Nvidia sales was in part because its valuation was "very high" and that it was consolidating its portfolio into higher conviction names.**\n\n"We like Nvidia, we think it\'s going to be a good stock. It\'s priced, it\'s the \'check-the-box\' AI company. For a flagship fund, where we\'re consolidated towards our highest conviction names, part of that has to do with the valuation," she told CNBC on February 27.\n\nWood is instead counting on UiPath for Ark Invest\'s exposure to artificial intelligence, which is its second largest position across all of its ETFs. Meanwhile, Tesla remains Ark Invest\'s top holding, which is also working on artificial intelligence to help enable its self-driving technology. \n\nBut despite the hype in AI this year, those two stocks have only captured some of the year-to-date gains seen across the space. Shares of UIPath are up just 14% year-to-date, while Tesla stock is up an impressive 50%. \n\nShares of Ark Invest\'s Disruptive Innovation ETF were down 2.7% on Thursday, despite the Nasdaq 100 jumping 1.7%. \n\nhttps://markets.businessinsider.com/news/stocks/cathie-wood-ark-invest-sold-nvidia-stake-before-ai-rally-2023-5?'

In [ ]:
dfSA = pd.DataFrame()
  
dfSA['score'] = df['score']
dfSA['num_comments'] = df['num_comments']
dfSA['body'] = df['body']

dfSA

   score  num_comments                                               body
0   2336           398  Cathie Wood's Ark Invest is probably wishing i...
1   1505          1402  He doesn't work at Google anymore, so no more ...
2   1379           475  https://www.cnbc.com/2023/05/30/nvidia-on-trac...
3   1213           488  https://www.cnbc.com/2023/05/27/white-house-an...
4   1206           688  The automaker's dip comes as competitor Ford M...
5   1171           859  Nvidia reported its fiscal first quarter earni...
6    897           217  example: Best Buy\n\nBest Buy somehow can see ...
7    888           344  It started off nice and good with some google,...
8    778           267  https://www.cnbc.com/2023/05/26/inflation-rose...
9    530           163  https://www.cnbc.com/2023/05/25/tesla-elon-mus...